name: BayesianCP
channels:
  - defaults
dependencies:
  - numpy
  - pandas
  - matplotlib
  - scipy
  - pymc
  - pytables
  - wxpython
  - dill
  - pip
  - pip:
    - autograd
    - future
    - pypubsub
    - mpi4py
