name: Bayesian
channels:
  - defaults
dependencies:
  - numpy==1.14.6
  - pandas==1.0.5
  - matplotlib==3.2.2
  - scipy=1.5.2
  - pymc==2.3.8
  - hdf5==1.10.6
  - pytables==3.6.1
  - wxpython==4.0.4
  - dill
  - pip
  - pip:
    - autograd
    - future
    - pypubsub
